# usage: crank --config https://raw.githubusercontent.com/DeagleGross/Benchmarks/refs/heads/dmkorolev/antiforgery-sample/scenarios/antiforgery.benchmarks.yml --scenario antiforgery --profile aspnet-perf-win --application.source.branchOrCommit dmkorolev/antiforgery-sample --application.source.repository https://github.com/DeagleGross/Benchmarks.git

imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Wrk/wrk.yml
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.HttpClient/httpclient.yml
  - https://github.com/aspnet/Benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true

variables:
  serverPort: 5000
  serverScheme: http

jobs:
  antiforgerybenchmarks:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/BenchmarksApps/Antiforgery/Antiforgery.csproj
    readyStateText: Application started.
    arguments: "--urls {{serverScheme}}://{{serverAddress}}:{{serverPort}}"

scenarios:

  antiforgery:
    application:
      job: antiforgerybenchmarks
      variables:
        scenario: antiforgery
    load:
      job: wrk
      variables:
        path: /getAndValidateToken