imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Wrk/wrk.yml
  - https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/aspnet.profiles.yml

variables:
  serverPort: 5000
  serverScheme: http
  scenario: antiforgery
  debug: false

jobs:
  antiforgerybenchmarks:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/BenchmarksApps/Antiforgery/Antiforgery.csproj
    readyStateText: Application started.
    arguments: "--urls {{serverScheme}}://{{serverAddress}}:{{serverPort}} --scenario {{scenario}} --debug {{debug}}"

scenarios:

  antiforgery-validation:
    application:
      job: antiforgerybenchmarks
      variables:
        scenario: antiforgery
    load:
      job: wrk
      variables:
        script: https://raw.githubusercontent.com/aspnet/Benchmarks/main/src/BenchmarksApps/Antiforgery/scripts/wrk-auth-token.lua

  antiforgery-generation:
    application:
      job: antiforgerybenchmarks
      variables:
        scenario: antiforgery
    load:
      job: wrk
      variables:
        path: /auth

  antiforgery-noop:
    application:
      job: antiforgerybenchmarks
      variables:
        scenario: antiforgery
    load:
      job: wrk
      variables:
        path: /noOp

  csrf-accepted:
    application:
      job: antiforgerybenchmarks
      variables:
        scenario: csrf
    load:
      job: wrk
      variables:
        path: /csrf
        script: https://raw.githubusercontent.com/aspnet/Benchmarks/main/src/BenchmarksApps/Antiforgery/scripts/wrk-csrf.lua
        customHeaders:
          - "Sec-Fetch-Site: same-origin"

  csrf-rejected:
    application:
      job: antiforgerybenchmarks
      variables:
        scenario: csrf
    load:
      job: wrk
      variables:
        path: /csrf
        script: https://raw.githubusercontent.com/aspnet/Benchmarks/main/src/BenchmarksApps/Antiforgery/scripts/wrk-csrf.lua
        customHeaders:
          - "Sec-Fetch-Site: cross-site"