imports:
  - https://github.com/aspnet/benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true

jobs:
  dotnet:
    source:
      repository: https://github.com/dotnet/performance
      branchOrCommit: main
      project: src/benchmarks/micro/MicroBenchmarks.csproj
    variables:
      filter: "*"
      job: short
    arguments: --job {{job}} --filter {{filter}} --memory
    framework: netcoreapp3.1
    options:
      benchmarkDotNet: true
      displayOutput: true
    
scenarios:

  custom:
    application:
      job: dotnet
      variables:
        # default filter to limit benchmarks if filter is not set
        filter: "*LinqBenchmarks*"

  linq:
    application:
      job: dotnet
      variables:
        filter: "*LinqBenchmarks*"

  sockets:
    application:
      job: dotnet
      variables:
        filter: "*SocketSendReceivePerfTest*"

profiles:
  local:
    jobs: 
      application:
        endpoints: 
          - http://localhost:5010
