imports:
  - https://raw.githubusercontent.com/dotnet/crank/master/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:
  mapaction:
    source:
      repository: https://github.com/aspnet/Benchmarks.git
      branchOrCommit: halter73/houdini
      project: src/BenchmarksApps/MapAction/MapAction.csproj
    readyStateText: Application started.

scenarios:
  echotodo:
    application:
      job: mapaction
    load:
      job: bombardier
      variables:
        verb: POST
        headers:
          jsonInput: '--header "content-type: application/json"'
        presetHeaders: 'jsonInput'
        path: /EchoTodo
        bodyFile: https://raw.githubusercontent.com/aspnet/Benchmarks/halter73/houdini/scenarios/assets/todo.json
profiles:
  local:
    variables:
      serverUri: http://localhost
    jobs: 
      application:
        endpoints: 
          - http://localhost:5010
      load:
        endpoints: 
          - http://localhost:5010
  aspnet-perf-lin:
    variables:
      serverUri: http://10.0.0.102
      cores: 12
    jobs:
      application:
        endpoints: 
          - http://asp-perf-lin:5001
      load:
        endpoints: 
          - http://asp-perf-load:5001
  aspnet-perf-win:
    variables:
      serverUri: http://10.0.0.110
      cores: 12
    jobs:
      application:
        endpoints: 
          - http://asp-perf-win:5001
      load:
        endpoints: 
          - http://asp-perf-db:5001
  aspnet-citrine-lin:
    variables:
      serverUri: http://10.0.0.102
      cores: 28
    jobs: 
      application:
        endpoints: 
          - http://asp-citrine-lin:5001
      load:
        endpoints: 
          - http://asp-citrine-load:5001
  aspnet-citrine-win:
    variables:
      serverUri: http://10.0.0.104
      cores: 28
    jobs: 
      application:
        endpoints: 
          - http://asp-citrine-win:5001
      load:
        endpoints: 
          - http://asp-citrine-db:5001
