# Local run:
# crank --config "C:\Users\knatalia\dev\git\Benchmarks\scenarios\httpclient.benchmarks.yml" --scenario get --profile local

imports:
  - https://github.com/aspnet/Benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true

variables:
    serverPort: 1234
    httpVersion: "1.1"
    numberOfClients: 10
    concurrencyPerClient: 10
    http11MaxConnectionsPerServer: 1
    http20EnableMultipleConnections: false
    warmup: 15
    duration: 60

scenarios:
  get:
    application:
      job: kestrel
    load:
      job: httpClient
      variables:
        scenario: get

jobs:
  kestrel:
    source:
      #repository: https://github.com/aspnet/benchmarks.git
      localFolder: C:\Users\knatalia\dev\git\Benchmarks
      branchOrCommit: main
      project: src/BenchmarksApps/HttpClientBenchmarks/Servers/Kestrel/Kestrel.csproj
    readyStateText: Application started # app should write this line to output! 
    arguments: "--urls https://{{serverAddress}}:{{serverPort}}"

  httpClient:
    source:
      #repository: https://github.com/aspnet/benchmarks.git
      localFolder: C:\Users\knatalia\dev\git\Benchmarks
      branchOrCommit: main
      project: src/BenchmarksApps/HttpClientBenchmarks/Clients/HttpClient/HttpClient.csproj
    isConsoleApp: true
    waitForExit: true
    arguments: "--url https://{{serverAddress}}:{{serverPort}} --scenario {{scenario}} --httpVersion {{httpVersion}} --numberOfClients {{numberOfClients}} --concurrencyPerClient {{concurrencyPerClient}} --http11MaxConnectionsPerServer {{http11MaxConnectionsPerServer}} {% if http20EnableMultipleConnections %} --http20EnableMultipleConnections {% endif %} --warmup {{warmup}} --duration {{duration}}"