# Local run:
# crank --config "C:\Users\knatalia\dev\git\Benchmarks\scenarios\httpclient.benchmarks.yml" --scenario get --profile local

imports:
  #- https://raw.githubusercontent.com/aspnet/Benchmarks/main/src/BenchmarksApps/HttpClientBenchmarks/Servers/Kestrel/Kestrel.yml
  #- https://raw.githubusercontent.com/aspnet/Benchmarks/main/src/BenchmarksApps/HttpClientBenchmarks/Clients/HttpClient/HttpClient.yml
  - https://github.com/aspnet/Benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true

variables:
    serverPort: 1234

scenarios:
  get:
    application:
      job: kestrel
    load:
      job: httpClient
      variables:
        scenario: get
        httpVersion: 1.1

jobs:
  kestrel: #- https://raw.githubusercontent.com/aspnet/Benchmarks/main/src/BenchmarksApps/HttpClientBenchmarks/Servers/Kestrel/Kestrel.yml
    source:
      #repository: https://github.com/aspnet/benchmarks.git
      localFolder: C:\Users\knatalia\dev\git\Benchmarks
      branchOrCommit: main
      project: src/BenchmarksApps/HttpClientBenchmarks/Servers/Kestrel/Kestrel.csproj
    readyStateText: Application started # app should write this line to output! 
    arguments: "--urls https://{{serverAddress}}:{{serverPort}}"

  httpClient: #- https://raw.githubusercontent.com/aspnet/Benchmarks/main/src/BenchmarksApps/HttpClientBenchmarks/Clients/HttpClient/HttpClient.yml
    source:
      #repository: https://github.com/aspnet/benchmarks.git
      localFolder: C:\Users\knatalia\dev\git\Benchmarks
      branchOrCommit: main
      project: src/BenchmarksApps/HttpClientBenchmarks/Clients/HttpClient/HttpClient.csproj
    isConsoleApp: true
    waitForExit: true
    arguments: "--url https://{{serverAddress}}:{{serverPort}} --scenario {{scenario}} --httpVersion {{httpVersion}}"