# Local run:
# crank --config "C:\Users\knatalia\dev\git\Benchmarks\scenarios\httpclient.benchmarks.yml" --scenario httpclient-kestrel-get --profile local

imports:
  - https://github.com/aspnet/Benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true

variables:
    serverPort: 5000
    httpVersion: "1.1"
    useHttps: false
    numberOfHttpClients: 1
    concurrencyPerHttpClient: 12
    http11MaxConnectionsPerServer: 2147483647
    http20EnableMultipleConnections: true
    warmup: 15
    duration: 30

scenarios:
  httpclient-kestrel-get:
    server:
      job: kestrel
    client:
      job: httpClient
      variables:
        scenario: get

jobs:
  kestrel:
    source:
      repository: https://github.com/CarnaViire/benchmarks.git #https://github.com/aspnet/benchmarks.git
      #localFolder: C:\Users\knatalia\dev\git\Benchmarks
      branchOrCommit: http3-benchmarks #main
      project: src/BenchmarksApps/HttpClientBenchmarks/Servers/Kestrel/Kestrel.csproj
    readyStateText: Application started # app should write this line to output -- default Kestrel logging does that
    arguments: "--urls http{% if useHttps %}s{% endif %}://{{serverAddress}}:{{serverPort}}"

  httpClient:
    source:
      repository: https://github.com/CarnaViire/benchmarks.git #https://github.com/aspnet/benchmarks.git
      #localFolder: C:\Users\knatalia\dev\git\Benchmarks
      branchOrCommit: http3-benchmarks #main
      project: src/BenchmarksApps/HttpClientBenchmarks/Clients/HttpClient/HttpClient.csproj
    isConsoleApp: true
    waitForExit: true
    arguments: "--url http{% if useHttps %}s{% endif %}://{{serverAddress}}:{{serverPort}} --scenario {{scenario}} --httpVersion {{httpVersion}} --numberOfHttpClients {{numberOfHttpClients}} --concurrencyPerHttpClient {{concurrencyPerHttpClient}} --http11MaxConnectionsPerServer {{http11MaxConnectionsPerServer}} {% if http20EnableMultipleConnections %} --http20EnableMultipleConnections {% endif %} --warmup {{warmup}} --duration {{duration}}"

profiles:
  local:
    variables:
      serverAddress: localhost
    jobs:
      server:
        endpoints: 
          - http://localhost:5010
      client:
        endpoints: 
          - http://localhost:5010

  aspnet-citrine-lin:
    variables:
      serverAddress: 10.0.0.102
      cores: 28
    jobs:
      server:
        endpoints: 
          - http://asp-citrine-client:5001
      client:
        endpoints: 
          - http://asp-citrine-lin:5001

  aspnet-citrine-lin-relay:
    variables:
      serverAddress: 10.0.0.102
      cores: 28
    jobs:
      server:
        endpoints: 
          - https://aspnetperf.servicebus.windows.net/citrineclient
      client:
        endpoints: 
          - https://aspnetperf.servicebus.windows.net/citrinelin

  aspnet-citrine-win:
    variables:
      serverAddress: 10.0.0.104
      cores: 28
    jobs:
      server:
        endpoints: 
          - http://asp-citrine-db:5001
      client:
        endpoints: 
          - http://asp-citrine-win:5001

  aspnet-citrine-win-relay:
    variables:
      serverAddress: 10.0.0.104
      cores: 28
    jobs:
      server:
        endpoints: 
          - https://aspnetperf.servicebus.windows.net/citrinedb
      client:
        endpoints: 
          - https://aspnetperf.servicebus.windows.net/citrinewin
          
  aspnet-citrine-arm:
    variables:
      serverAddress: 10.0.0.107
      cores: 32
    jobs:
      server:
        endpoints: 
          - http://asp-citrine-client:5001
      client:
        endpoints: 
          - http://asp-citrine-arm:5001
  
  aspnet-citrine-arm-relay:
    variables:
      serverAddress: 10.0.0.107
      cores: 32
    jobs:
      server:
        endpoints: 
          - https://aspnetperf.servicebus.windows.net/citrineclient
      client:
        endpoints: 
          - https://aspnetperf.servicebus.windows.net/citrinearm
          
  aspnet-citrine-amd:
    variables:
      serverAddress: 10.0.0.106
      cores: 48
    jobs:
      server:
        endpoints: 
          - http://asp-citrine-db:5001
      client:
        endpoints: 
          - http://asp-citrine-amd:5001
  
  aspnet-citrine-amd-relay:
    variables:
      serverAddress: 10.0.0.106
      cores: 48
    jobs:
      server:
        endpoints: 
          - https://aspnetperf.servicebus.windows.net/citrinedb
      client:
        endpoints: 
          - https://aspnetperf.servicebus.windows.net/citrineamd

  aspnet-perf-lin:
    variables:
      serverAddress: 10.0.0.102
      cores: 12
    jobs:
      server:
        endpoints: 
          - http://asp-perf-client:5001
      client:
        endpoints: 
          - http://asp-perf-lin:5001

  aspnet-perf-lin-relay:
    variables:
      serverAddress: 10.0.0.102
      cores: 12
    jobs:
      server:
        endpoints: 
          - https://aspnetperf.servicebus.windows.net/perfclient
      client:
        endpoints: 
          - https://aspnetperf.servicebus.windows.net/perflin

  aspnet-perf-win:
    variables:
      serverAddress: 10.0.0.110
      cores: 12
    jobs:
      server:
        endpoints: 
          - http://asp-perf-db:5001
      client:
        endpoints: 
          - http://asp-perf-win:5001

  aspnet-perf-win-relay:
    variables:
      serverAddress: 10.0.0.110
      cores: 12
    jobs:
      server:
        endpoints: 
          - https://aspnetperf.servicebus.windows.net/perfdb
      client:
        endpoints: 
          - https://aspnetperf.servicebus.windows.net/perfwin