# Examples:
# --config mono.benchmarks.yml --scenario plaintext-mono-jit --profile aspnet-citrine-lin

imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Wrk/wrk.yml
  - https://github.com/aspnet/Benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true

variables:
    serverPort: 5000

jobs:
  platformbenchmarks:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/BenchmarksApps/Kestrel/PlatformBenchmarks/PlatformBenchmarks.csproj
    readyStateText: Application started.
    framework: net5.0

  aspnetbenchmarks:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/Benchmarks/Benchmarks.csproj
    readyStateText: Application started.
    variables:
      protocol: http
      serverScheme: http
      server: Kestrel
      transport: Sockets
      scenario: plaintext
      database: ''
    arguments: "--nonInteractive true --scenarios {{scenario}} --urls {{serverScheme}}://{{serverAddress}}:{{serverPort}} --server {{server}} --kestrelTransport {{transport}} --protocol {{protocol}} {% if database.size > 0 %} --database {{ database }} {% endif %}"

  postgresql:
    source:
      repository: https://github.com/TechEmpower/FrameworkBenchmarks.git
      branchOrCommit: master
      dockerFile: toolset/databases/postgres/postgres.dockerfile
      dockerImageName: postgres_te
      dockerContextDirectory: toolset/databases/postgres
    readyStateText: Future log output will go to log
    noClean: true

scenarios:
  plaintextPlatform-coreclr:
    application:
      job: platformbenchmarks
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /plaintext
        pipeline: 16

  plaintextPlatform-mono-jit:
    application:
      job: platformbenchmarks
      useMonoRuntime: jit
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /plaintext
        pipeline: 16

  plaintextPlatform-mono-jit-preemptive:
    application:
      job: platformbenchmarks
      useMonoRuntime: jit
      environmentVariables:
        MONO_THREADS_SUSPEND : preemptive
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /plaintext
        pipeline: 16

  plaintextPlatform-mono-llvm-jit:
    application:
      job: platformbenchmarks
      useMonoRuntime: llvm-jit
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /plaintext
        pipeline: 16

  plaintextPlatform-mono-llvm-aot:
    application:
      job: platformbenchmarks
      useMonoRuntime: llvm-aot
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /plaintext
        pipeline: 16

  plaintextPlatform-mono-llvm-aot-preemptive:
    application:
      job: platformbenchmarks
      useMonoRuntime: llvm-aot
      environmentVariables:
        MONO_THREADS_SUSPEND : preemptive
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /plaintext
        pipeline: 16

  jsonPlatform-coreclr:
    application:
      job: platformbenchmarks
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /json
        connections: 512

  jsonPlatform-mono-jit:
    application:
      job: platformbenchmarks
      useMonoRuntime: jit
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /json
        connections: 512

  jsonPlatform-mono-llvm-jit:
    application:
      job: platformbenchmarks
      useMonoRuntime: llvm-jit
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /json
        connections: 512

  jsonPlatform-mono-llvm-aot:
    application:
      job: platformbenchmarks
      useMonoRuntime: llvm-aot
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /json
        connections: 512

  fortunesPlatform-coreclr:
    db:
      job: postgresql
    application:
      job: platformbenchmarks
      buildArguments: 
        - "/p:IsDatabase=true"
      environmentVariables:
        database: PostgreSQL
        connectionstring: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;Enlist=false;Max Auto Prepare=4;Multiplexing=true;Write Coalescing Delay Us=500;Write Coalescing Buffer Threshold Bytes=1000
    load:
      job: wrk
      variables:
        presetHeaders: html
        path: /fortunes
        connections: 512

  fortunesPlatform-mono-jit:
    db:
      job: postgresql
    application:
      job: platformbenchmarks
      useMonoRuntime: jit
      buildArguments: 
        - "/p:IsDatabase=true"
      environmentVariables:
        database: PostgreSQL
        connectionstring: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;Enlist=false;Max Auto Prepare=4;Multiplexing=true;Write Coalescing Delay Us=500;Write Coalescing Buffer Threshold Bytes=1000
    load:
      job: wrk
      variables:
        presetHeaders: html
        path: /fortunes
        connections: 512

  fortunesPlatform-mono-llvm-jit:
    db:
      job: postgresql
    application:
      job: platformbenchmarks
      useMonoRuntime: llvm-jit
      buildArguments: 
        - "/p:IsDatabase=true"
      environmentVariables:
        database: PostgreSQL
        connectionstring: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;Enlist=false;Max Auto Prepare=4;Multiplexing=true;Write Coalescing Delay Us=500;Write Coalescing Buffer Threshold Bytes=1000
    load:
      job: wrk
      variables:
        presetHeaders: html
        path: /fortunes
        connections: 512
  
  fortunesPlatform-mono-llvm-aot:
    db:
      job: postgresql
    application:
      job: platformbenchmarks
      useMonoRuntime: llvm-aot
      buildArguments: 
        - "/p:IsDatabase=true"
      environmentVariables:
        database: PostgreSQL
        connectionstring: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;Enlist=false;Max Auto Prepare=4;Multiplexing=true;Write Coalescing Delay Us=500;Write Coalescing Buffer Threshold Bytes=1000
    load:
      job: wrk
      variables:
        presetHeaders: html
        path: /fortunes
        connections: 512

  plaintext-coreclr:
    application:
      job: aspnetbenchmarks
      variables:
        scenario: plaintext
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /plaintext
        pipeline: 16
        warmup: 5
        duration: 10

  plaintext-mono-jit:
    application:
      job: aspnetbenchmarks
      useMonoRuntime: jit
      variables:
        scenario: plaintext
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /plaintext
        pipeline: 16
        warmup: 5
        duration: 10

  plaintext-mono-llvm-jit:
    application:
      job: aspnetbenchmarks
      useMonoRuntime: llvm-jit
      variables:
        scenario: plaintext
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /plaintext
        pipeline: 16
        warmup: 5
        duration: 10

  plaintext-mono-llvm-aot:
    application:
      job: aspnetbenchmarks
      useMonoRuntime: llvm-aot
      variables:
        scenario: plaintext
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /plaintext
        pipeline: 16
        warmup: 5
        duration: 10

  json-coreclr:
    application:
      job: aspnetbenchmarks
      variables:
        scenario: json
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /json
        warmup: 5
        duration: 10

  json-mono-jit:
    application:
      job: aspnetbenchmarks
      useMonoRuntime: jit
      variables:
        scenario: json
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /json
        warmup: 5
        duration: 10

  json-mono-llvm-jit:
    application:
      job: aspnetbenchmarks
      useMonoRuntime: llvm-jit
      variables:
        scenario: json
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /json
        warmup: 5
        duration: 10

  json-mono-llvm-aot:
    application:
      job: aspnetbenchmarks
      useMonoRuntime: llvm-aot
      variables:
        scenario: json
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /json
        warmup: 5
        duration: 10

  fortunes-coreclr:
    db:
      job: postgresql
    application:
      job: aspnetbenchmarks
      variables:
        scenario: DbFortunesRaw
      environmentVariables:
        database: PostgresQL
        connectionString: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;NoResetOnClose=true;Enlist=false;Max Auto Prepare=4
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /fortunes/raw

  fortunes-mono-jit:
    db:
      job: postgresql
      useMonoRuntime: jit
    application:
      job: aspnetbenchmarks
      variables:
        scenario: DbFortunesRaw
      environmentVariables:
        database: PostgresQL
        connectionString: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;NoResetOnClose=true;Enlist=false;Max Auto Prepare=4
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /fortunes/raw

  fortunes-mono-llvm-jit:
    db:
      job: postgresql
      useMonoRuntime: llvm-jit
    application:
      job: aspnetbenchmarks
      variables:
        scenario: DbFortunesRaw
      environmentVariables:
        database: PostgresQL
        connectionString: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;NoResetOnClose=true;Enlist=false;Max Auto Prepare=4
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /fortunes/raw

  fortunes-mono-llvm-aot:
    db:
      job: postgresql
      useMonoRuntime: llvm-aot
    application:
      job: aspnetbenchmarks
      variables:
        scenario: DbFortunesRaw
      environmentVariables:
        database: PostgresQL
        connectionString: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;NoResetOnClose=true;Enlist=false;Max Auto Prepare=4
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /fortunes/raw

  single_query-coreclr:
    db:
      job: postgresql
    application:
      job: platformbenchmarks
      buildArguments: 
        - "/p:IsDatabase=true"
      environmentVariables:
        database: PostgreSQL
        connectionstring: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;Enlist=false;Max Auto Prepare=4;Multiplexing=true;Write Coalescing Delay Us=500;Write Coalescing Buffer Threshold Bytes=1000
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /db

  single_query-mono-jit:
    db:
      job: postgresql
    application:
      job: platformbenchmarks
      useMonoRuntime: jit
      buildArguments: 
        - "/p:IsDatabase=true"
      environmentVariables:
        database: PostgreSQL
        connectionstring: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;Enlist=false;Max Auto Prepare=4;Multiplexing=true;Write Coalescing Delay Us=500;Write Coalescing Buffer Threshold Bytes=1000
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /db

  single_query-mono-llvm-jit:
    db:
      job: postgresql
    application:
      job: platformbenchmarks
      useMonoRuntime: llvm-jit
      buildArguments: 
        - "/p:IsDatabase=true"
      environmentVariables:
        database: PostgreSQL
        connectionstring: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;Enlist=false;Max Auto Prepare=4;Multiplexing=true;Write Coalescing Delay Us=500;Write Coalescing Buffer Threshold Bytes=1000
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /db

  single_query-mono-llvm-aot:
    db:
      job: postgresql
    application:
      job: platformbenchmarks
      useMonoRuntime: llvm-aot
      buildArguments: 
        - "/p:IsDatabase=true"
      environmentVariables:
        database: PostgreSQL
        connectionstring: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;Enlist=false;Max Auto Prepare=4;Multiplexing=true;Write Coalescing Delay Us=500;Write Coalescing Buffer Threshold Bytes=1000
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /db

  multiple_queries-coreclr:
    db:
      job: postgresql
    application:
      job: platformbenchmarks
      buildArguments: 
        - "/p:IsDatabase=true"
      environmentVariables:
        database: PostgreSQL
        connectionstring: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;NoResetOnClose=true;Enlist=false;Max Auto Prepare=4
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /queries/queries=20

  multiple_queries-mono-jit:
    db:
      job: postgresql
    application:
      job: platformbenchmarks
      useMonoRuntime: jit
      buildArguments: 
        - "/p:IsDatabase=true"
      environmentVariables:
        database: PostgreSQL
        connectionstring: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;NoResetOnClose=true;Enlist=false;Max Auto Prepare=4
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /queries/queries=20

  multiple_queries-mono-llvm-jit:
    db:
      job: postgresql
    application:
      job: platformbenchmarks
      useMonoRuntime: llvm-jit
      buildArguments: 
        - "/p:IsDatabase=true"
      environmentVariables:
        database: PostgreSQL
        connectionstring: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;NoResetOnClose=true;Enlist=false;Max Auto Prepare=4
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /queries/queries=20

  multiple_queries-mono-llvm-aot:
    db:
      job: postgresql
    application:
      job: platformbenchmarks
      useMonoRuntime: llvm-aot
      buildArguments: 
        - "/p:IsDatabase=true"
      environmentVariables:
        database: PostgreSQL
        connectionstring: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;NoResetOnClose=true;Enlist=false;Max Auto Prepare=4
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /queries/queries=20

  updates-coreclr:
    db:
      job: postgresql
    application:
      job: platformbenchmarks
      buildArguments: 
        - "/p:IsDatabase=true"
      environmentVariables:
        database: PostgreSQL
        connectionString: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;NoResetOnClose=true;Enlist=false;Max Auto Prepare=4
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /updates/queries=20

  updates-mono-jit:
    db:
      job: postgresql
    application:
      job: platformbenchmarks
      useMonoRuntime: jit
      buildArguments: 
        - "/p:IsDatabase=true"
      environmentVariables:
        database: PostgreSQL
        connectionString: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;NoResetOnClose=true;Enlist=false;Max Auto Prepare=4
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /updates/queries=20

  updates-mono-llvm-jit:
    db:
      job: postgresql
    application:
      job: platformbenchmarks
      useMonoRuntime: llvm-jit
      buildArguments: 
        - "/p:IsDatabase=true"
      environmentVariables:
        database: PostgreSQL
        connectionString: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;NoResetOnClose=true;Enlist=false;Max Auto Prepare=4
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /updates/queries=20

  updates-mono-llvm-aot:
    db:
      job: postgresql
    application:
      job: platformbenchmarks
      useMonoRuntime: llvm-aot
      buildArguments: 
        - "/p:IsDatabase=true"
      environmentVariables:
        database: PostgreSQL
        connectionString: Server={{databaseServer}};Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;NoResetOnClose=true;Enlist=false;Max Auto Prepare=4
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /updates/queries=20
