imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Wrk/wrk.yml
  - https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/aspnet.profiles.yml

variables:
  serverPort: 5000
  serverScheme: http
  scenario: antiforgery
  debug: false

jobs:
  antiforgerybenchmarks:
    source:
      #repository: https://github.com/cdincer/Benchmarks.git
      localFolder: ../
      branchOrCommit: main
      project: src/BenchmarksApps/Rewrite/Rewrite.csproj
    readyStateText: Application started.
    arguments: "--urls {{serverScheme}}://{{serverAddress}}:{{serverPort}} --scenario {{scenario}} --debug {{debug}}"

scenarios:

  rewrite1:
    application:
      job: antiforgerybenchmarks
      variables:
        scenario: antiforgery
    load:
      job: wrk
      variables:
        path: /rewrite1

  antiforgery-generation:
    application:
      job: antiforgerybenchmarks
      variables:
        scenario: antiforgery
    load:
      job: wrk
      variables:
        path: /auth