# Example:
# crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/socket.benchmarks.yml --scenario basic-server-client --profile aspnet-perf-lin

imports:
  - https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/aspnet.profiles.standard.yml

variables:
    warmup: 15 #seconds
    duration: 15 #seconds
    connections: 8
    serverPort: 5000
    receiveBufferSize: 32768
    sendBufferSize: 32768

scenarios:
  connection-establishment:
    server:
      job: basic-server
      agent: secondary
      variables:
        scenario: ConnectionEstablishment
    client:
      job: basic-client
      agent: main
      variables:
        host: '{{secondaryAddress}}'
        scenario: ConnectionEstablishment
  
  read-write-tcp:
    server:
      job: basic-server
      agent: secondary
      variables:
        scenario: ReadWrite
    client:
      job: basic-client
      agent: main
      variables:
        host: '{{secondaryAddress}}'
        scenario: ReadWrite

jobs:
  basic-server:
    source:
      localFolder: C:\Users\aaksoy\Desktop\dotnet\aspnet-Benchmarks
      project: src/BenchmarksApps/SocketBenchmarks/Servers/Basic/SocketBenchmarks.Servers.Basic.csproj
    readyStateText: Listening on
    arguments: '--port {{serverPort}} --receive-buffer-size {{receiveBufferSize}} --send-buffer-size {{sendBufferSize}} --scenario {{scenario}}'

  basic-client:
    source:
      localFolder: C:\Users\aaksoy\Desktop\dotnet\aspnet-Benchmarks
      project: src/BenchmarksApps/SocketBenchmarks/Clients/Basic/SocketBenchmarks.Clients.Basic.csproj
    isConsoleApp: true
    waitForExit: true
    timeout: 120 #seconds
    arguments: '--endpoint {{host}}:{{serverPort}} --warmup-time {{warmup}} --duration {{duration}} --receive-buffer-size {{receiveBufferSize}} --send-buffer-size {{sendBufferSize}} --connections {{connections}} --scenario {{scenario}}'
