# Examples:
# --config staticfiles.benchmarks.yml --scenario static --profile aspnet-perf-lin

imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Wrk/wrk.yml
  - https://github.com/aspnet/Benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true

jobs:
  benchmark:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/BenchmarksApps/StaticFiles/StaticFiles.csproj
    readyStateText: Application started.
    variables:
      filename: file.txt
      sizeInBytes: 1024
    arguments: "--filename {{filename}} --size {{sizeInBytes}}"
  
scenarios:
  static:
    application:
      job: benchmark
      variables:
        filename: file.txt
        sizeInBytes: 1024
    load:
      job: wrk
      variables:
        path: /file.txt
