imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Wrk/wrk.yml
  - https://github.com/aspnet/Benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true

jobs:
  aspnet:
    source:
      repository: https://github.com/TechEmpower/FrameworkBenchmarks.git
      branchOrCommit: master
      dockerContextDirectory: frameworks/CSharp/aspnetcore/
    readyStateText: Application started.

  nodejs:
    source:
      repository: https://github.com/TechEmpower/FrameworkBenchmarks.git
      branchOrCommit: master
      dockerFile: frameworks/JavaScript/nodejs/nodejs.dockerfile
      dockerImageName: nodejs
      dockerContextDirectory: frameworks/JavaScript/nodejs/
    readyStateText: NodeJS worker listening
    arguments: --add-host="tfb-database:{{databaseServer}}"

  actix:
    source:
      repository: https://github.com/TechEmpower/FrameworkBenchmarks.git
      branchOrCommit: master
      dockerFile: frameworks/Rust/actix/actix-raw.dockerfile
      dockerImageName: actix_raw
      dockerContextDirectory: frameworks/Rust/actix/
    readyStateText: Started http server
    arguments: --add-host="tfb-database:{{databaseServer}}"

  fasthttp:
    source:
      repository: https://github.com/TechEmpower/FrameworkBenchmarks.git
      branchOrCommit: master
      dockerFile: frameworks/Go/fasthttp/fasthttp-prefork.dockerfile
      dockerImageName: fasthttp_prefork
      dockerContextDirectory: frameworks/Go/fasthttp/
    arguments: --add-host="tfb-database:{{databaseServer}}"

  ulib:
    source:
      repository: https://github.com/TechEmpower/FrameworkBenchmarks.git
      branchOrCommit: master
      dockerContextDirectory: frameworks/C++/ulib/
    # readyStateText: Started http server
    port: 8080
    arguments: --add-host="tfb-database:{{databaseServer}}"

  netty:
    source:
      repository: https://github.com/TechEmpower/FrameworkBenchmarks.git
      branchOrCommit: master
      dockerFile: frameworks/Java/netty/netty.dockerfile
      dockerImageName: netty
      dockerContextDirectory: frameworks/Java/netty/
    readyStateText: Httpd started
    arguments: --add-host="tfb-database:{{databaseServer}}"

  postgresql:
    source:
      repository: https://github.com/TechEmpower/FrameworkBenchmarks.git
      branchOrCommit: master
      dockerFile: toolset/databases/postgres/postgres.dockerfile
      dockerImageName: postgres_te
      dockerContextDirectory: toolset/databases/postgres
    readyStateText: ready to accept connections
    noClean: true

  mysql:
    source:
      repository: https://github.com/TechEmpower/FrameworkBenchmarks.git
      branchOrCommit: master
      dockerFile: toolset/databases/mysql/mysql.dockerfile
      dockerImageName: mysql_te
      dockerContextDirectory: toolset/databases/mysql
    readyStateText: ready for connections
    noClean: true

scenarios:

  # NodeJS
  plaintext_nodejs:
    db:
      # nodejs image requires mysql to be available
      job: mysql
    application:
      job: nodejs
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /plaintext
        pipeline: 16
        serverPort: 8080

  json_nodejs:
    db:
      # nodejs image requires mysql to be available
      job: mysql
    application:
      job: nodejs
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /json
        serverPort: 8080

  fortunes_nodejs:
    db:
      job: mysql
    application:
      job: nodejs
    load:
      job: wrk
      variables:
        presetHeaders: html
        path: /fortunes
        serverPort: 8080

  # Actix (Rust)
  plaintext_actix:
    application:
      job: actix
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /plaintext
        pipeline: 16
        serverPort: 8080

  json_actix:
    application:
      job: actix
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /json
        serverPort: 8080

  fortunes_actix:
    db:
      job: postgresql
    application:
      job: actix
      source:
          dockerFile: frameworks/Rust/actix/actix-pg.dockerfile
          dockerImageName: actix_pg
    load:
      job: wrk
      variables:
        presetHeaders: html
        path: /fortunes
        serverPort: 8080

  # FastHttp (Go)
  plaintext_fasthttp:
    db:
      job: postgresql
    application:
      job: fasthttp
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /plaintext
        pipeline: 16
        serverPort: 8080

  json_fasthttp:
    db:
      job: postgresql
    application:
      job: fasthttp
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /json
        serverPort: 8080

  fortunes_fasthttp:
    db:
      job: postgresql
    application:
      job: fasthttp
    load:
      job: wrk
      variables:
        presetHeaders: html
        path: /fortunes
        serverPort: 8080

  # Ulib (C++)
  plaintext_ulib:
    application:
      job: ulib
      source:
          dockerFile: frameworks/C++/ulib/ulib.dockerfile
          dockerImageName: ulib_plaintext
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /plaintext
        pipeline: 16
        serverPort: 8080

  json_ulib:
    application:
      job: ulib
      source:
          dockerFile: frameworks/C++/ulib/ulib-json.dockerfile
          dockerImageName: ulib_json
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /json
        serverPort: 8080

  fortunes_ulib:
    db:
      job: postgresql
    application:
      job: ulib
      source:
          dockerFile: frameworks/C++/ulib/ulib-postgres.dockerfile
          dockerImageName: ulib_postgres
    load:
      job: wrk
      variables:
        presetHeaders: html
        path: /fortune
        serverPort: 8080

  # Netty (Java)
  plaintext_netty:
    application:
      job: netty
    load:
      job: wrk
      variables:
        presetHeaders: plaintext
        path: /plaintext
        pipeline: 16
        serverPort: 8080

  json_netty:
    application:
      job: netty
    load:
      job: wrk
      variables:
        presetHeaders: json
        path: /json
        serverPort: 8080

  fortunes_aspnet:
    db:
      job: postgresql
    application:
      job: aspnet
      source:
          dockerFile: frameworks/CSharp/aspnetcore/aspcore-mw-ado-pg.dockerfile
          dockerImageName: aspcore-mw-ado-pg
    load:
      job: wrk
      variables:
        presetHeaders: html
        path: /fortunes/raw
        serverPort: 8080

  fortunes_mysql_aspnet:
    db:
      job: mysql
    application:
      job: aspnet
      source:
          dockerFile: frameworks/CSharp/aspnetcore/aspcore-mw-ado-my.dockerfile
          dockerImageName: aspcore-mw-ado-my
    load:
      job: wrk
      variables:
        presetHeaders: html
        path: /fortunes/raw
        serverPort: 8080
