imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Wrk/wrk.yml
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.HttpClient/httpclient.yml
  - https://github.com/aspnet/Benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true

variables:
  serverPort: 5000

jobs:
  httpSysServer:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/BenchmarksApps/TLS/HttpSys/HttpSys.csproj
    readyStateText: Application started.
    variables:
      mTLS: false # enables settings on http.sys to negotiate client cert on connections
      tlsRenegotiation: false # enables client cert validation
      certValidationConsoleEnabled: false
      httpSysLogs: false
      statsEnabled: false
    arguments: "--urls https://{{serverAddress}}:{{serverPort}} --mTLS {{mTLS}} --certValidationConsoleEnabled {{certValidationConsoleEnabled}} --statsEnabled {{statsEnabled}} --tlsRenegotiation {{tlsRenegotiation}} --httpSysLogs {{httpSysLogs}}"

  kestrelServer:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/BenchmarksApps/TLS/Kestrel/Kestrel.csproj
    readyStateText: Application started.
    variables:
      mTLS: false
      tlsRenegotiation: false
      certValidationConsoleEnabled: false
      statsEnabled: false
    arguments: "--urls https://{{serverAddress}}:{{serverPort}} --mTLS {{mTLS}} --certValidationConsoleEnabled {{certValidationConsoleEnabled}} --statsEnabled {{statsEnabled}} --tlsRenegotiation {{tlsRenegotiation}}"

scenarios:

# HTTP.SYS

  tls-handshakes-httpsys:
    application:
      job: httpSysServer
    load:
      job: wrk
      variables:
        path: /hello-world
        presetHeaders: connectionclose
        connections: 32
        serverScheme: https

  mTls-handshakes-httpsys:
    application:
      job: httpSysServer
      variables:
        mTLS: true # enables settings on http.sys to negotiate client cert on connections
        tlsRenegotiation: true # enables client cert validation
        httpSysLogs: false # only for debug purposes
        certValidationConsoleEnabled: false # only for debug purposes
        serverPort: 8080 # IMPORTANT: not to intersect with other tests in case http.sys configuration impacts other benchmarks
    load:
      job: httpclient
      variables:
        serverPort: 8080 # in sync with server
        path: /hello-world
        presetHeaders: connectionclose
        connections: 32
        serverScheme: https
        certPath: https://raw.githubusercontent.com/aspnet/Benchmarks/refs/heads/main/src/BenchmarksApps/TLS/HttpSys/testCert.pfx
        certPwd: testPassword

  tls-renegotiation-httpsys:
    application:
      job: httpSysServer
      variables:
        mTLS: false
        tlsRenegotiation: true
        httpSysLogs: false # only for debug purposes
        certValidationConsoleEnabled: false # only for debug purposes
    load:
      job: httpclient
      variables:
        path: /hello-world
        presetHeaders: connectionclose
        connections: 32
        serverScheme: https
        certPath: https://raw.githubusercontent.com/aspnet/Benchmarks/refs/heads/main/src/BenchmarksApps/TLS/HttpSys/testCert.pfx
        certPwd: testPassword

# Kestrel
  
  tls-handshakes-kestrel:
    application:
      job: kestrelServer
    load:
      job: wrk
      variables:
        path: /hello-world
        presetHeaders: connectionclose
        connections: 32
        serverScheme: https

  mTls-handshakes-kestrel:
    application:
      job: kestrelServer
      variables:
        mTLS: true
        certValidationConsoleEnabled: false # only for debug purposes
    load:
      job: httpclient
      variables:
        path: /hello-world
        presetHeaders: connectionclose
        connections: 32
        serverScheme: https
        certPath: https://raw.githubusercontent.com/aspnet/Benchmarks/refs/heads/main/src/BenchmarksApps/TLS/Kestrel/testCert.pfx
        certPwd: testPassword

  tls-renegotiation-kestrel:
    application:
      job: kestrelServer
      variables:
        mTLS: false
        tlsRenegotiation: true
        certValidationConsoleEnabled: false # only for debug purposes
    load:
      job: httpclient
      variables:
        path: /hello-world
        presetHeaders: connectionclose
        connections: 32
        serverScheme: https
        certPath: https://raw.githubusercontent.com/aspnet/Benchmarks/refs/heads/main/src/BenchmarksApps/TLS/Kestrel/testCert.pfx
        certPwd: testPassword