jobs:
  httpClient:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/BenchmarksApps/HttpClientBenchmarks/Clients/HttpClient/HttpClient.csproj
    isConsoleApp: true
    waitForExit: true
    arguments: "--url https://{{serverAddress}}:{{serverPort}} --scenario {{scenario}}"
