variables:
  headers:
    none: ''
    plaintext: "--header Accept:text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7"
    html: "--header Accept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    json: "--header Accept:application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7"
    connectionclose: "--header Connection:close"
  presetHeaders: none

jobs:
  bombardier:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: master
      project: src/BombardierClient/BombardierClient.csproj
    readyStateText: Bombardier Client
    sdkVersion: 3.0.100
    aspNetCoreVersion: '3.0'
    runtimeVersion: '3.0'
    waitForExit: true
    variables:
      connections: 256
      duration: 15
      warmup: 0
      rate: 0
      transport: fasthttp # | http1 | http2
    arguments: "-c {{connections}} -d {{duration}}s -w {{warmup}}s --insecure -l {% if rate != 0 %} --rate {{ rate }} {% endif %} {% if transport %} --{{ transport}} {% endif %} {{headers[presetHeaders]}} {{serverUri}}:{{serverPort}}{{path}}"
