jobs:
  websocketClient:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/WebsocketClient/WebsocketClient.csproj
    readyStateText: Websocket Client
    waitForExit: true
    variables:
      connections: 100
      warmup: 5
      duration: 15
      scenario: echo
      path: /Echo
      serverScheme: ws
      serverAddress: localhost
      serverPort: 5000
      collectLatency: true
      compress: false
      size: 1000
    arguments: "-c {{connections}} -w {{warmup}} -d {{duration}} -s {{scenario}} -u {{serverScheme}}://{{serverAddress}}:{{serverPort}}{{path}}{% if collectLatency != blank %} --latency {{ collectLatency }}{% endif %} --size {{size}} --compress {{compress}}"
