
jobs:
  signalrServer:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/BenchmarksApps/SignalR/BenchmarkServer.csproj
    readyStateText: Application started
    waitForExit: false
    arguments: "--urls {{serverScheme}}://{{serverAddress}}:{{serverPort}}"
    
