
jobs:
  signalrServer:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: master
      project: src/BenchmarksApps/SignalR/BenchmarkServer.csproj
    readyStateText: Application started
    runtimeVersion: '5.0.*'
    waitForExit: false
