# Examples:
# --config benchmarks.fortunes.yml --scenario fortunesplatform --profile aspnet-citrine

imports:
  - https://raw.githubusercontent.com/aspnet/Benchmarks/master/src/BombardierClient/bombardier.yml
  - https://raw.githubusercontent.com/aspnet/Benchmarks/master/src/WrkClient/wrk.yml

jobs:
  platformbenchmarks:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: master
      project: src/BenchmarksApps/Kestrel/PlatformBenchmarks/PlatformBenchmarks.csproj
    readyStateText: Application started.

  postgresql:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: master
      dockerFile: docker/postgres-techempower/Dockerfile
      dockerImageName: postgres
      dockerContextDirectory: docker/postgres-techempower
    readyStateText: PostgreSQL init process complete

scenarios:
  fortunesplatform:
    db:
      job: postgresql

    application:
      job: platformbenchmarks
      buildArguments: 
        - "/p:IsDatabase=true"

    load:
      job: bombardier
      variables:
        presetHeaders: html
        path: /fortunes
        warmup: 5 
        duration: 10
        serverPort: 5000

profiles:
  aspnet-citrine:
    variables:
      serverUri: http://10.0.0.102
      cores: 28
    jobs: 
      db:
        endpoints: 
          - http://asp-citrine-amd:5001
      application:
        endpoints: 
          - http://asp-citrine-lin:5001
        environmentVariables:
          database: PostgreSQL
          connectionstring: Server=10.0.0.106;Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;NoResetOnClose=true;Enlist=false;Max Auto Prepare=4
      load:
        variables:
          connections: 512
        endpoints: 
          - http://asp-citrine-win:5001

