jobs:
  lighthouse:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: mbuck/lighthouse-metrics
      dockerImageName: lighthouse
      dockerContextDirectory: src/BenchmarksApps/Lighthouse/
      dockerFile: src/BenchmarksApps/Lighthouse/Dockerfile
    environmentVariables:
      TARGET_URL: "{{serverScheme}}://{{serverAddress}}:{{serverPort}}{{subPath}}"
    readyStateText: Generating Lighthouse report
    noClean: true
    waitForExit: true
