# Examples:
# --config benchmarks.compose.yml --scenario plaintext --variable serverUri=http://10.0.0.102

imports:
  - https://raw.githubusercontent.com/aspnet/Benchmarks/master/src/Wrk2Client/wrk2.yml
  - https://raw.githubusercontent.com/aspnet/Benchmarks/master/src/BombardierClient/bombardier.yml
  - https://raw.githubusercontent.com/aspnet/Benchmarks/master/src/WrkClient/wrk.yml
  - https://raw.githubusercontent.com/aspnet/Benchmarks/master/src/PipeliningClient/pipelining.yml
jobs:
  aspnetbenchmarks:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: master
      project: src/Benchmarks/Benchmarks.csproj
    readyStateText: Application started.
    variables:
      connection-header: "--header Connection:keep-alive"
      protocol: http
      server: Kestrel
      transport: Sockets
      scenario: plaintext
    arguments: "--nonInteractive true --scenarios {{scenario}} --urls {{protocol}}://[*]:{{serverPort}} --server {{server}} --kestrelTransport {{transport}} --protocol {{protocol}}"
  postgresql:
    source:
      repository: https://github.com/TechEmpower/FrameworkBenchmarks.git
      branchOrCommit: master
      dockerFile: toolset/databases/postgres/postgres.dockerfile
      dockerImageName: postgres
      dockerContextDirectory: toolset/databases/postgres/
    scenario: PostgresQL
scenarios:
  plaintext:
    application:
      job: aspnetbenchmarks
      variables:
        scenario: plaintext
    load:
      job: bombardier
      variables:
        presetHeaders: plaintext
        path: /plaintext
        duration: 15
        warmup: 5
        serverPort: 5000

profiles:
  aspnet-physical:
    variables:
      serverUri: http://10.0.0.102
      cores: 12
    jobs:
      application:
        endpoints: 
          - http://asp-perf-lin:5001
      load:
        endpoints: 
          - http://asp-perf-load:5001
