variables:
  headers:
    none: ''
    plaintext: "--header Accept:text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7"
    html: "--header Accept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    json: "--header Accept:application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7"
    connectionclose: "--header Connection:close"
  presetHeaders: none

jobs:
  wrk:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: master
      project: src/WrkClient/WrkClient.csproj
    readyStateText: 'Running '
    waitForExit: true
    variables:
      connections: 256  # total number of HTTP connections to keep open with each thread handling N = connections/threads
      duration: 15 # duration in seconds
      warmup: 0 # warmup in seconds
      threads: 32 # total number of threads to use
      pipeline: 1
      script: '' # path or url of a LUA script, e.g., https://raw.githubusercontent.com/wg/wrk/master/scripts/post.lua
      scriptArguments: '' # arguments passed to the script, e.g., 16
    requiredVariables:
      serverUri: http://10.0.0.102
      serverPort: 5000
    arguments: "-c {{connections}} {{serverUri}}:{{serverPort}}{{path}} --latency -d {{duration}}s -w {{warmup}}s -t {{threads}} {{headers[presetHeaders]}} {% if pipeline > 1 %} -s scripts/pipeline.lua -- {{ pipeline }} {% elsif script.length > 0  %} -s {{script}} -- {{scriptArguments}} {% endif %}"
