jobs:
  mvcServer:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/BenchmarksApps/Mvc/Mvc.csproj
    readyStateText: Application started
    waitForExit: false
    variables:
      useNewtonsoftJson: false
      useAsymmetricKey: false
      serverScheme: http
      serverPort: 5000
    arguments: "--urls {{serverScheme}}://{{serverAddress}}:{{serverPort}} {%if useNewtonsoftJson == true %} --useNewtonsoftJson true {% endif %} {%if useAsymmetricKey == true %} --useAsymmetricKey true {% endif %}"
  mapaction:
    source:
      repository: https://github.com/aspnet/Benchmarks.git
      branchOrCommit: main
      project: src/BenchmarksApps/MapAction/MapAction.csproj
    readyStateText: Application started.
