imports:
  - https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/aspnet.profiles.standard.yml
  
scenarios:
  blazorwasm:
    application:
      job: buildperformance
      variables:
        build_scenario: blazorwasm
  blazorwasm-hosted:
    application:
      job: buildperformance
      variables:
        build_scenario: blazorwasm-hosted
  blazorserver:
    application:
      job: buildperformance
      variables:
        build_scenario: blazorserver
  mvc:
    application:
      job: buildperformance
      variables:
        build_scenario: mvc
  api:
    application:
      job: buildperformance
      variables:
        build_scenario: api
jobs:
  buildperformance:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/BenchmarksApps/BuildPerformance/BuildPerformance.csproj
    readyStateText: Running scenario
    waitForExit: true
    selfContained: false
    variables:
      build_scenario: blazorwasm
      verboseLogs: false
      performanceSummary: false
      bl: false
    arguments: '-s {{build_scenario}} -v {{verboseLogs}} --performanceSummary {{performanceSummary}} --bl {{bl}}'
    options:
      downloadFiles: 
        - "{% if bl == 'true' %}msbuild.binlog{% endif %}"
   