scenarios:
  blazorwasm:
    application:
      job: buildperformance
      variables:
        build_scenario: blazorwasm
  blazorwasm-hosted:
    application:
      job: buildperformance
      variables:
        build_scenario: blazorwasm-hosted
  blazorserver:
    application:
      job: buildperformance
      variables:
        build_scenario: blazorserver
  mvc:
    application:
      job: buildperformance
      variables:
        build_scenario: mvc
  api:
    application:
      job: buildperformance
      variables:
        build_scenario: api
jobs:
  buildperformance:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/BenchmarksApps/BuildPerformance/BuildPerformance.csproj
    readyStateText: Running scenario
    waitForExit: true
    selfContained: false
    variables:
      build_scenario: blazorwasm
      verboseLogs: false
      performanceSummary: false
    arguments: '-s {{build_scenario}} -v {{verboseLogs}} --performanceSummary {{performanceSummary}}'

profiles:
  aspnet-citrine-arm:
    variables:
      serverPort: 5000
      serverAddress: 10.0.0.107
      cores: 32
    jobs:
      db:
        endpoints:
          - http://asp-citrine-db:5001
      application:
        endpoints:
          - http://asp-citrine-arm:5001
        variables:
          databaseServer: 10.0.0.103
      load:
        endpoints:
          - http://asp-citrine-load:5001
