scenarios:
  blazorwasm:
    application:
      job: buildperformance
      variables:
        build_scenario: blazorwasm
  blazorwasm-hosted:
    application:
      job: buildperformance
      variables:
        build_scenario: blazorwasm-hosted
  blazorserver:
    application:
      job: buildperformance
      variables:
        build_scenario: blazorserver
  mvc:
    application:
      job: buildperformance
      variables:
        build_scenario: mvc
  api:
    application:
      job: buildperformance
      variables:
        build_scenario: api
jobs:
  buildperformance:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: prkrishn/test
      project: src/BenchmarksApps/BuildPerformance/BuildPerformance.csproj
    readyStateText: Application started
    waitForExit: true
    selfContained: false
    variables:
      build_scenario: blazorwasm
      verboseLogs: false
    arguments: '-s {{build_scenario}} -v {{verboseLogs}}'

profiles:
  aspnet-citrine-lin:
    variables:
      serverPort: 5000
      serverAddress: 10.0.0.102
      cores: 28
    jobs:
      db:
        endpoints:
          - http://asp-perf-db:5001
      application:
        endpoints:
          - http://asp-citrine-lin:5001
        variables:
          databaseServer: 10.0.0.103
      load:
        endpoints:
          - http://asp-citrine-load:5001

  aspnet-citrine-win:
    variables:
      serverPort: 5000
      serverAddress: 10.0.0.104
      cores: 28
    jobs:
      db:
        endpoints:
          - http://asp-citrine-db:5001
      application:
        endpoints:
          - http://asp-citrine-win:5001
        variables:
          databaseServer: 10.0.0.103
      load:
        endpoints:
          - http://asp-citrine-load:5001

  aspnet-citrine-arm:
    variables:
      serverPort: 5000
      serverAddress: 10.0.0.107
      cores: 32
    jobs:
      db:
        endpoints:
          - http://asp-citrine-db:5001
      application:
        endpoints:
          - http://asp-citrine-arm:5001
        variables:
          databaseServer: 10.0.0.103
      load:
        endpoints:
          - http://asp-citrine-load:5001

  aspnet-citrine-amd:
    variables:
      serverPort: 5000
      serverAddress: 10.0.0.106
      cores: 48
    jobs:
      db:
        endpoints:
          - http://asp-citrine-db:5001
      application:
        endpoints:
          - http://asp-citrine-amd:5001
        variables:
          databaseServer: 10.0.0.103
      load:
        endpoints:
          - http://asp-citrine-load:5001

  aspnet-perf-lin:
    variables:
      serverPort: 5000
      serverAddress: 10.0.0.102
      cores: 12
    jobs:
      db:
        endpoints:
          - http://asp-perf-db:5001
      application:
        endpoints:
          - http://asp-perf-lin:5001
        variables:
          databaseServer: 10.0.0.103
      load:
        endpoints:
          - http://asp-perf-load:5001

  aspnet-perf-win:
    variables:
      serverPort: 5000
      serverAddress: 10.0.0.110
      cores: 12
    jobs:
      db:
        endpoints:
          - http://asp-perf-load:5001
      application:
        endpoints:
          - http://asp-perf-win:5001
        variables:
          databaseServer: 10.0.0.104
      load:
        endpoints:
          - http://asp-perf-db:5001
