
jobs:
  websocketServer:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/BenchmarksApps/Websocket/BenchmarkServer.csproj
    readyStateText: Application started
    runtimeVersion: '5.0.*'
    waitForExit: false
