
jobs:
  websocketServer:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/BenchmarksApps/Websocket/BenchmarkServer.csproj
    readyStateText: Application started
    waitForExit: false
    variables:
      serverScheme: http
    arguments: "--urls {{serverScheme}}://{{serverAddress}}:{{serverPort}}"
